### ISSUE TITLE
December Tasks for Robocon2019

### ISSUE THREAD

**Issue by shashank3199** [RoboManipal-9-0/Competitions#10]
**Task priority**: HIGH

# Task description
Agendas for December

**Person assigned**
Task assigned to @shashank3199 , @adis98 and @akshatha-k 

# Must Haves
### Autonomous -
- [ ] ROS: @adis98 and @shashank3199 . To be completed over December.
- [x] OpenCV: @shashank3199 and @akshatha-k . To be completed before 5th December.
- [x] Dynamixels Testing: @shashank3199 . Testing and Setting of Appropriate IDs. To be Completed by 2nd December.
- [x] BeagleBone and Raspberry Pi: @shashank3199 . Installing and Testing OpenCV by 5th December.

### Manual -
- [ ] Library Patches: @akshatha-k . Library Testing for PS2Controller and ServoChain Library. 
- [ ] Loading Mechanism: @adis98 and @akshatha-k . Testing with Confirmed Design. To be done by 15th December.
- [ ] LSA - Autonomous : @shashank3199. Testing for the Forest Zone.
 
## Extras
- [ ] Full-Fledged Manual Bot Testing(With respect to Robocon Arena): @adis98 and @akshatha-k . To be completed with everything mounted by 15th Decemeber.
