### ISSUE TITLE
Base motion without feedback

### ISSUE THREAD

**Issue by TheProjectsGuy** [RoboManipal-9-0/Competitions#2]
# Main goals
- [ ] Get the bot moving using the `Serial interface`
    - [ ] Libraries and modification patch fixes
    - [ ] Rotation on point
    - [ ] Protocol for serial
    - [ ] PID Controller using library  (_Simulated sensor_, work in the end only)
- [ ] Get the bot moving using the `PS2`
    - [ ] Using the PS2 controller library
    - [ ] _Everything in Serial interface_

[![Badge](https://img.shields.io/badge/competition-ABU%20RoboCon-brightgreen.svg)](https://github.com/RoboManipal-9-0/Competitions/tree/master/RoboCon2019)

**Comment by TheProjectsGuy** [comment]
# Task distribution
The following deadline have been planned

| Done | Developer | Deadline | Job | 
|:---: | :---: | :---: | :---: |
|  | @akshatha-k | `17-October-2018` | PS2 |
|  | @shashank3199 | `4-October-2018` | Libraries and modification patches | 
|  | @shashank3199 and @akshatha-k  | `6-October-2018` | On point rotation patch |
|  | @adis98 | `17-October-2018` | Serial implementation (with protocol) |
