### ISSUE TITLE
Serial implementation of manual bot motion without feedback

### ISSUE THREAD

**Issue by adis98** [RoboManipal-9-0/Competitions#4]
**Task priority**
The priority of the task [HIGH]

**Task description**
Implementing the motion of Manual bot using Serial communication with a bluetooth module. Without feedback.

**People assigned**
Task assigned to  [@adis98]  [@shashank3199]

# Must Haves
- [x] Use the D45 library for motion(older one)
- [x] Use the new NWCH library
- [x] Use bluetooth module
- [x] Joystick app
- [x] Testing motion (without app)
- [x] Testing motion (with app)
- [x] Testing motion (with new app) 

## Extras
Need to include feedback mechanism.
