### ISSUE TITLE
Base motion using PS2 with feedback

### ISSUE THREAD

**Issue by akshatha-k** [RoboManipal-9-0/Competitions#5]
**Task priority**: HIGH

## Task Description 
- Have the bot moving without feedback with the PS2 controller i.e including speed and direction control. PS2Controller must also be modified to be compatible with the future modes of simple and autonomous line following.

Person assigned : @akshatha-k 
Deadline: 17-10-2018

Must haves
- [x] Test and update the PS2 controller library.
- [x] Function in the library to toggle modes e.g, to toggle between simple and 
       autonomous line following.
 - [x] Basic bot motion with controller.
 - [ ] PID controller using library.
