### ISSUE TITLE
Lock Anti-Phase Mode for Base Motion

### ISSUE THREAD

**Issue by shashank3199** [RoboManipal-9-0/Competitions#7]
**Task priority**
The priority of the task [HIGH]

**Task description**
Adding the Lock Anti-Phase Mode for the Base with respect to Electronic Wiring from the Default Shield and Testing.<br>
Since the Current Shield is designed such that the Dir Pins of the Motor Drivers can be connected to Digital Pins only, thus require Relimate Modification such that they can be connect to PWM compatible pins of Board and can receive analog values. 

**People assigned**
Task assigned to  [@shashank3199] and Electronics Team.

# Must Haves
- [ ] New Pair Relimates (two for Lock Anti-Phase and old two for Sign-Magnitude Mode).
- [ ] Testing Motion (without app).
- [ ] Testing Motion (with app).
- [ ] Testing Motion (with PS2 Controller).
