### ISSUE TITLE
Throwing Mechanism

### ISSUE THREAD

**Issue by shashank3199** [RoboManipal-9-0/Competitions#8]
**Task priority**
The priority of the task [HIGH]

**Task description**
Coding the Mechanism for the Throwing of the Shagai and Adding it to the Manual Bot Code.

**People assigned**
Task assigned to [@shashank3199] and [@adis98].

# Must-Haves
- [x] Testing Throwing Mechanism Mechanically with Button Actuation. 
- [x] Testing Throwing Mechanism Electronically using Relays.
- [ ] Testing Loading Mechanism Mechanically.
- [ ] Testing Loading Mechanism with Electronics. 
- [ ] Testing Complete Mechanism with Bot Code.
- [ ] Testing Complete Mechanism with Motion using PS2 Controller.
