### ISSUE TITLE
Autonomous bot simulation (Stage 1)

### ISSUE THREAD

**Issue by TheProjectsGuy** [RoboManipal-9-0/Competitions#9]
**Task priority** : **HIGH**

# Task description
Simulate the quadruped on Gazebo simulator. The result must be the following
1) Get the framework for any locomotion simulation ready
    ```
    [X, Y] values of end effector -> (Motor sequence generator) -> [R1, R2]
    ```
2) .world file for the arena 

**Person assigned**: @TheProjectsGuy and @shashank3199 

# Must Haves
- [x] Create STL files for individual parts, label them and put that up in the documentation (STL models on A360 hub and screenshots with key dimensions in the documentation)
- [x] Create a XACRO file for the robot, have statically modifiable parameters 
- [ ] Make a joint state publisher that publishes the joint values
- [ ] Arena as a `.world` file
- [ ] Create a .gazebo file for the launch
- [x] Spawn model in Gazebo
- [ ] Create a `.launch` file to ease everything
- [ ] Plot everything using rqt tools
- [ ] Have the bot moving
    - [ ] Test plugin for the spawning (simple python spawn_urdf node)
    - [ ] Test a plugin for publishing joint states in gazebo

**Comment by TheProjectsGuy** [comment]
@shashank3199 Finish the first point by tomorrow afternoon (**12<sup>th</sup> November 2018, 12:00 PM**). The task is
```
Create STL files for individual parts, label them and put that up in the documentation (STL models on A360 hub and screenshots with key dimensions in the documentation)
```
Once you're done with that, I'll create the XACRO and then you can test the robot model in RViz.
Upload the files on A360 hub for this repository. We'll check the documentation later.

**Comment by shashank3199** [comment]
Click [here](https://a360.co/2PoCGyn) to view Body STL File.
Click [here](https://a360.co/2PmL2H5) to view Link_1 STL File.
Click [here](https://a360.co/2FqRFTQ) to view Link_2 STL File.
